### ISSUE TITLE
Change tag line

### ISSUE THREAD

**Issue by esheldon** [conda-forge/ngmix-feedstock#12]
Issue:  Tag line says the code is implemented in C.  Mabye "Gaussian mixtures and image processing implemented in python and numba"?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by beckermr** [comment]
Sure. Change the recipe and it should get fixed automagically!
